name: Kanshi
options:
  deploymentTarget:
    macOS: "14.0"
  bundleIdPrefix: com.ruaylabs

targets:
  Kanshi:
    type: application
    platform: macOS
    sources:
      - path: Kanshi
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME)"
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: Kanshi/Info.plist
        CODE_SIGN_ENTITLEMENTS: Kanshi/Kanshi.entitlements
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: "5.0"
      configs:
        debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited) DEBUG"
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        release:
          SWIFT_COMPILATION_MODE: wholemodule
    info:
      path: Kanshi/Info.plist
      properties:
        LSUIElement: true
